//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskList.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceComponentes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceComponentes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskList.Model.Resources.ResourceComponentes", typeof(ResourceComponentes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string BOTAO_NOVO {
            get {
                return ResourceManager.GetString("BOTAO_NOVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BOTAO_SUBMIT_SALVAR {
            get {
                return ResourceManager.GetString("BOTAO_SUBMIT_SALVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BOTAO_VOLTAR_PARA_LISTAGEM {
            get {
                return ResourceManager.GetString("BOTAO_VOLTAR_PARA_LISTAGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tarefa.
        /// </summary>
        public static string TITULO_TELA_EDITAR_TAREFA {
            get {
                return ResourceManager.GetString("TITULO_TELA_EDITAR_TAREFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Tarefa.
        /// </summary>
        public static string TITULO_TELA_INCLUIR_TAREFA {
            get {
                return ResourceManager.GetString("TITULO_TELA_INCLUIR_TAREFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas.
        /// </summary>
        public static string TITULO_TELA_LISTAGEM_TAREFA {
            get {
                return ResourceManager.GetString("TITULO_TELA_LISTAGEM_TAREFA", resourceCulture);
            }
        }
    }
}
